services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tokyo
      POSTGRES_PASSWORD: tokyo
      POSTGRES_DB: tokyo_moment
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
